FROM python:3.10-slim

WORKDIR /app

# ✅ fix OpenCV + mediapipe
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libgl1 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

EXPOSE 8000

# 👉 ถ้าใช้ FastAPI แนะนำอันนี้
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]